version: "3"
services:
  kademliaBootstrap:
    image: kademlia:latest
    stdin_open: true
    tty: true
    hostname: kademliaBootstrap
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
#    ports:
#      - "3330:80"
   # networks:
    #  - kademlia_network
  kademliaNodes:
    image: kademlia:latest
    stdin_open: true
    tty: true
    links:
      - kademliaBootstrap:kademliaBootstrap
    deploy:
      replicas: 2 
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
#    ports:
#      - "4000:80"
    #networks:
    #  - kademlia_network
      
networks:
  kademlia_network:
